# Generated by Django 4.2.4 on 2023-08-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100)),
                ('copyright_year', models.PositiveIntegerField()),
                ('site_url', models.URLField()),
            ],
        ),
    ]
