# Generated by Django 4.2.4 on 2023-08-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_personalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
