# Generated by Django 4.2.4 on 2023-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=100)),
                ('section_link', models.CharField(max_length=100)),
            ],
        ),
    ]
