# Generated by Django 4.2.4 on 2023-08-15 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_navlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=150)),
                ('icon_class', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('fa_icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.faicon')),
            ],
        ),
    ]
